"""Pydantic schemas package."""

from src.schemas.common import PaginatedResponse, Pagination
from src.schemas.product import (
    ProductCreate,
    ProductUpdate,
    ProductRead,
    ProductListItem,
    ProductSummary,
    ProductImageCreate,
    ProductImageRead,
    ProductAttributeCreate,
    ProductAttributeRead,
)
from src.schemas.category import (
    CategoryCreate,
    CategoryUpdate,
    CategoryRead,
    CategoryWithChildren,
    ProductCategoryCreate,
    ProductCategoryRead,
)
from src.schemas.channel_listing import (
    ChannelListingCreate,
    ChannelListingUpdate,
    ChannelListingRead,
)
from src.schemas.inventory import (
    LocationCreate,
    LocationUpdate,
    LocationRead,
    StockItemCreate,
    StockItemUpdate,
    StockItemRead,
    StockMovementCreate,
    StockMovementRead,
)
from src.schemas.vendor import (
    VendorCreate,
    VendorUpdate,
    VendorRead,
    VendorListItem,
    VendorStatsSummary,
    VendorContactCreate,
    VendorContactUpdate,
    VendorContactRead,
    VendorAddressCreate,
    VendorAddressUpdate,
    VendorAddressRead,
    VendorDocumentCreate,
    VendorDocumentUpdate,
    VendorDocumentRead,
    VendorProductCreate,
    VendorProductUpdate,
    VendorProductRead,
)
from src.schemas.purchase_order import (
    PurchaseOrderCreate,
    PurchaseOrderUpdate,
    PurchaseOrderRead,
    PurchaseOrderListItem,
    POLineCreate,
    POLineUpdate,
    POLineRead,
    ReceiveItemsRequest,
    TrackingUpdate,
    FollowUpUpdate,
    LogContactRequest,
    CreateFromVendorRequest,
)

__all__ = [
    # Common
    "PaginatedResponse",
    "Pagination",
    # Products
    "ProductCreate",
    "ProductUpdate",
    "ProductRead",
    "ProductListItem",
    "ProductSummary",
    "ProductImageCreate",
    "ProductImageRead",
    "ProductAttributeCreate",
    "ProductAttributeRead",
    # Categories
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryRead",
    "CategoryWithChildren",
    "ProductCategoryCreate",
    "ProductCategoryRead",
    # Channel Listings
    "ChannelListingCreate",
    "ChannelListingUpdate",
    "ChannelListingRead",
    # Inventory
    "LocationCreate",
    "LocationUpdate",
    "LocationRead",
    "StockItemCreate",
    "StockItemUpdate",
    "StockItemRead",
    "StockMovementCreate",
    "StockMovementRead",
    # Vendors
    "VendorCreate",
    "VendorUpdate",
    "VendorRead",
    "VendorListItem",
    "VendorStatsSummary",
    "VendorContactCreate",
    "VendorContactUpdate",
    "VendorContactRead",
    "VendorAddressCreate",
    "VendorAddressUpdate",
    "VendorAddressRead",
    "VendorDocumentCreate",
    "VendorDocumentUpdate",
    "VendorDocumentRead",
    "VendorProductCreate",
    "VendorProductUpdate",
    "VendorProductRead",
    # Purchase Orders
    "PurchaseOrderCreate",
    "PurchaseOrderUpdate",
    "PurchaseOrderRead",
    "PurchaseOrderListItem",
    "POLineCreate",
    "POLineUpdate",
    "POLineRead",
    "ReceiveItemsRequest",
    "TrackingUpdate",
    "FollowUpUpdate",
    "LogContactRequest",
    "CreateFromVendorRequest",
]
