"""product_catalog_tables

Revision ID: 8700014c0d8f
Revises: 92db5d03da7e
Create Date: 2026-02-01 17:48:04.825120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8700014c0d8f'
down_revision: Union[str, None] = '92db5d03da7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amazonBrowseNode', sa.String(), nullable=True),
    sa.Column('shopifyProductType', sa.String(), nullable=True),
    sa.Column('walmartCategoryId', sa.String(), nullable=True),
    sa.Column('googleCategoryId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Category_parentId'), 'Category', ['parentId'], unique=False)
    op.create_index(op.f('ix_Category_slug'), 'Category', ['slug'], unique=True)
    op.create_index(op.f('ix_Category_tenantId'), 'Category', ['tenantId'], unique=False)
    op.create_table('Location',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('WAREHOUSE', 'FBA', 'THREEPEL', 'STORE', name='LocationType'), nullable=False),
    sa.Column('channel', sa.Enum('AMAZON', 'SHOPIFY', 'WALMART', 'EBAY', name='Channel'), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Location_isActive'), 'Location', ['isActive'], unique=False)
    op.create_index(op.f('ix_Location_tenantId'), 'Location', ['tenantId'], unique=False)
    op.create_index(op.f('ix_Location_type'), 'Location', ['type'], unique=False)
    op.create_table('Order',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('channel', sa.Enum('AMAZON', 'SHOPIFY', 'WALMART', 'EBAY', name='Channel'), nullable=False),
    sa.Column('channelOrderId', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ALLOCATED', 'PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='OrderStatus'), nullable=False),
    sa.Column('customer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shippingAddress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('placedAt', sa.DateTime(), nullable=False),
    sa.Column('shippedAt', sa.DateTime(), nullable=True),
    sa.Column('deliveredAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_Order_placedAt'), 'Order', ['placedAt'], unique=False)
    op.create_index(op.f('ix_Order_status'), 'Order', ['status'], unique=False)
    op.create_index(op.f('ix_Order_tenantId'), 'Order', ['tenantId'], unique=False)
    op.create_table('Product',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('productType', sa.Enum('SIMPLE', 'PARENT', 'VARIATION', name='ProductType'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='ProductStatus'), nullable=False),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.Column('variationType', sa.String(), nullable=True),
    sa.Column('variationValue', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('modelNumber', sa.String(), nullable=True),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('ean', sa.String(), nullable=True),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('mpn', sa.String(), nullable=True),
    sa.Column('shortDescription', sa.Text(), nullable=True),
    sa.Column('longDescription', sa.Text(), nullable=True),
    sa.Column('bulletPoints', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('searchTerms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('seoTitle', sa.String(), nullable=True),
    sa.Column('seoDescription', sa.Text(), nullable=True),
    sa.Column('weightValue', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('weightUnit', sa.String(), nullable=True),
    sa.Column('lengthValue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('widthValue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('heightValue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dimensionUnit', sa.String(), nullable=True),
    sa.Column('pkgWeightValue', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('pkgWeightUnit', sa.String(), nullable=True),
    sa.Column('pkgLengthValue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pkgWidthValue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pkgHeightValue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pkgDimensionUnit', sa.String(), nullable=True),
    sa.Column('countryOfOrigin', sa.String(), nullable=True),
    sa.Column('hazmat', sa.Boolean(), nullable=False),
    sa.Column('hazmatInfo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ageRestriction', sa.Integer(), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('warrantyInfo', sa.String(), nullable=True),
    sa.Column('costPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('msrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_Product_asin'), 'Product', ['asin'], unique=False)
    op.create_index(op.f('ix_Product_brand'), 'Product', ['brand'], unique=False)
    op.create_index(op.f('ix_Product_parentId'), 'Product', ['parentId'], unique=False)
    op.create_index(op.f('ix_Product_status'), 'Product', ['status'], unique=False)
    op.create_index(op.f('ix_Product_tenantId'), 'Product', ['tenantId'], unique=False)
    op.create_index(op.f('ix_Product_upc'), 'Product', ['upc'], unique=False)
    op.create_table('Vendor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legalName', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('taxId', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('tier', sa.Enum('STRATEGIC', 'PREFERRED', 'STANDARD', 'PROBATION', 'SUSPENDED', name='VendorTier'), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('billingAddress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('leadTimeDays', sa.Integer(), nullable=False),
    sa.Column('minOrderValue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paymentTerms', sa.String(), nullable=True),
    sa.Column('creditLimit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('accountManagerName', sa.String(), nullable=True),
    sa.Column('accountManagerEmail', sa.String(), nullable=True),
    sa.Column('preferredContactMethod', sa.String(), nullable=True),
    sa.Column('contractStartDate', sa.DateTime(), nullable=True),
    sa.Column('contractEndDate', sa.DateTime(), nullable=True),
    sa.Column('insuranceExpiry', sa.DateTime(), nullable=True),
    sa.Column('w9OnFile', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internalNotes', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('onboardedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_Vendor_contractEndDate'), 'Vendor', ['contractEndDate'], unique=False)
    op.create_index(op.f('ix_Vendor_isActive'), 'Vendor', ['isActive'], unique=False)
    op.create_index(op.f('ix_Vendor_tenantId'), 'Vendor', ['tenantId'], unique=False)
    op.create_index(op.f('ix_Vendor_tier'), 'Vendor', ['tier'], unique=False)
    op.create_table('ChannelListing',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('AMAZON', 'SHOPIFY', 'WALMART', 'EBAY', name='Channel'), nullable=False),
    sa.Column('channelSku', sa.String(), nullable=False),
    sa.Column('channelProductId', sa.String(), nullable=True),
    sa.Column('channelVariantId', sa.String(), nullable=True),
    sa.Column('externalId', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bulletPoints', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('searchTerms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('compareAtPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maxPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fulfillmentChannel', sa.Enum('MERCHANT', 'MARKETPLACE', 'DROPSHIP', 'THREEPEL', name='FulfillmentChannel'), nullable=False),
    sa.Column('handlingDays', sa.Integer(), nullable=True),
    sa.Column('bufferStock', sa.Integer(), nullable=False),
    sa.Column('maxQuantity', sa.Integer(), nullable=True),
    sa.Column('listingUrl', sa.String(), nullable=True),
    sa.Column('channelData', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'ACTIVE', 'INACTIVE', 'SUPPRESSED', 'ERROR', name='ListingStatus'), nullable=False),
    sa.Column('syncedAt', sa.DateTime(), nullable=True),
    sa.Column('lastError', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_ChannelListing_productId'), 'ChannelListing', ['productId'], unique=False)
    op.create_index(op.f('ix_ChannelListing_status'), 'ChannelListing', ['status'], unique=False)
    op.create_index(op.f('ix_ChannelListing_tenantId'), 'ChannelListing', ['tenantId'], unique=False)
    op.create_table('OrderLine',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orderId', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('channelSku', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allocatedFromId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['allocatedFromId'], ['Location.id'], ),
    sa.ForeignKeyConstraint(['orderId'], ['Order.id'], ),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OrderLine_orderId'), 'OrderLine', ['orderId'], unique=False)
    op.create_index(op.f('ix_OrderLine_productId'), 'OrderLine', ['productId'], unique=False)
    op.create_table('ProductAttribute',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_ProductAttribute_name'), 'ProductAttribute', ['name'], unique=False)
    op.create_index(op.f('ix_ProductAttribute_productId'), 'ProductAttribute', ['productId'], unique=False)
    op.create_table('ProductCategory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('categoryId', sa.String(), nullable=False),
    sa.Column('isPrimary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['Category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_ProductCategory_categoryId'), 'ProductCategory', ['categoryId'], unique=False)
    op.create_index(op.f('ix_ProductCategory_productId'), 'ProductCategory', ['productId'], unique=False)
    op.create_table('ProductImage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('altText', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sizeBytes', sa.Integer(), nullable=True),
    sa.Column('mimeType', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ProductImage_position'), 'ProductImage', ['position'], unique=False)
    op.create_index(op.f('ix_ProductImage_productId'), 'ProductImage', ['productId'], unique=False)
    op.create_table('PurchaseOrder',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('poNumber', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('destinationId', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'CONFIRMED', 'SHIPPED', 'PARTIAL', 'RECEIVED', 'CANCELLED', name='POStatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orderedAt', sa.DateTime(), nullable=True),
    sa.Column('expectedAt', sa.DateTime(), nullable=True),
    sa.Column('shippedAt', sa.DateTime(), nullable=True),
    sa.Column('receivedAt', sa.DateTime(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('trackingNumber', sa.String(), nullable=True),
    sa.Column('trackingUrl', sa.String(), nullable=True),
    sa.Column('shipmentStatus', sa.Enum('PENDING', 'LABEL_CREATED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', name='ShipmentStatus'), nullable=True),
    sa.Column('lastTrackingUpdate', sa.DateTime(), nullable=True),
    sa.Column('lastContactedAt', sa.DateTime(), nullable=True),
    sa.Column('nextFollowUpAt', sa.DateTime(), nullable=True),
    sa.Column('followUpNotes', sa.Text(), nullable=True),
    sa.Column('vendorOrderNumber', sa.String(), nullable=True),
    sa.Column('vendorInvoiceNumber', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destinationId'], ['Location.id'], ),
    sa.ForeignKeyConstraint(['vendorId'], ['Vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PurchaseOrder_nextFollowUpAt'), 'PurchaseOrder', ['nextFollowUpAt'], unique=False)
    op.create_index(op.f('ix_PurchaseOrder_poNumber'), 'PurchaseOrder', ['poNumber'], unique=True)
    op.create_index(op.f('ix_PurchaseOrder_shipmentStatus'), 'PurchaseOrder', ['shipmentStatus'], unique=False)
    op.create_index(op.f('ix_PurchaseOrder_status'), 'PurchaseOrder', ['status'], unique=False)
    op.create_index(op.f('ix_PurchaseOrder_tenantId'), 'PurchaseOrder', ['tenantId'], unique=False)
    op.create_index(op.f('ix_PurchaseOrder_vendorId'), 'PurchaseOrder', ['vendorId'], unique=False)
    op.create_table('StockItem',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('locationId', sa.String(), nullable=False),
    sa.Column('quantityAvailable', sa.Integer(), nullable=False),
    sa.Column('quantityReserved', sa.Integer(), nullable=False),
    sa.Column('quantityInbound', sa.Integer(), nullable=False),
    sa.Column('reorderPoint', sa.Integer(), nullable=True),
    sa.Column('reorderQty', sa.Integer(), nullable=True),
    sa.Column('costBasis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('binLocation', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['locationId'], ['Location.id'], ),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_StockItem_locationId'), 'StockItem', ['locationId'], unique=False)
    op.create_index(op.f('ix_StockItem_quantityAvailable'), 'StockItem', ['quantityAvailable'], unique=False)
    op.create_index(op.f('ix_StockItem_tenantId'), 'StockItem', ['tenantId'], unique=False)
    op.create_table('VendorAddress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CORPORATE', 'BILLING', 'WAREHOUSE', 'RETURNS', 'OTHER', name='AddressType'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('isPrimary', sa.Boolean(), nullable=False),
    sa.Column('street1', sa.String(), nullable=False),
    sa.Column('street2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postalCode', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('taxJurisdiction', sa.String(), nullable=True),
    sa.Column('ftzZone', sa.String(), nullable=True),
    sa.Column('portOfEntry', sa.String(), nullable=True),
    sa.Column('contactName', sa.String(), nullable=True),
    sa.Column('contactPhone', sa.String(), nullable=True),
    sa.Column('contactEmail', sa.String(), nullable=True),
    sa.Column('shippingNotes', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendorId'], ['Vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VendorAddress_country'), 'VendorAddress', ['country'], unique=False)
    op.create_index(op.f('ix_VendorAddress_type'), 'VendorAddress', ['type'], unique=False)
    op.create_index(op.f('ix_VendorAddress_vendorId'), 'VendorAddress', ['vendorId'], unique=False)
    op.create_table('VendorContact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('GENERAL', 'SALES', 'ACCOUNT', 'SUPPORT', 'BILLING', 'SHIPPING', 'EXECUTIVE', name='ContactRole'), nullable=False),
    sa.Column('isPrimary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendorId'], ['Vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VendorContact_role'), 'VendorContact', ['role'], unique=False)
    op.create_index(op.f('ix_VendorContact_vendorId'), 'VendorContact', ['vendorId'], unique=False)
    op.create_table('VendorDocument',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('W9', 'W8', 'COI', 'CONTRACT', 'PRICE_LIST', 'CATALOG', 'SPEC_SHEET', 'CERTIFICATE', 'LICENSE', 'IMPORT_PERMIT', 'OTHER', name='DocumentType'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('objectKey', sa.String(), nullable=False),
    sa.Column('mimeType', sa.String(), nullable=False),
    sa.Column('sizeBytes', sa.Integer(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('uploadedBy', sa.String(), nullable=True),
    sa.Column('uploadedAt', sa.DateTime(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendorId'], ['Vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VendorDocument_expiresAt'), 'VendorDocument', ['expiresAt'], unique=False)
    op.create_index(op.f('ix_VendorDocument_type'), 'VendorDocument', ['type'], unique=False)
    op.create_index(op.f('ix_VendorDocument_vendorId'), 'VendorDocument', ['vendorId'], unique=False)
    op.create_table('VendorProduct',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('vendorSku', sa.String(), nullable=False),
    sa.Column('vendorProductName', sa.String(), nullable=True),
    sa.Column('unitCost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('minOrderQty', sa.Integer(), nullable=False),
    sa.Column('orderMultiple', sa.Integer(), nullable=False),
    sa.Column('casePackQty', sa.Integer(), nullable=True),
    sa.Column('leadTimeDays', sa.Integer(), nullable=True),
    sa.Column('isPreferred', sa.Boolean(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('lastOrderedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ),
    sa.ForeignKeyConstraint(['vendorId'], ['Vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_VendorProduct_isPreferred'), 'VendorProduct', ['isPreferred'], unique=False)
    op.create_index(op.f('ix_VendorProduct_productId'), 'VendorProduct', ['productId'], unique=False)
    op.create_table('POLine',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('poId', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('quantityOrdered', sa.Integer(), nullable=False),
    sa.Column('quantityReceived', sa.Integer(), nullable=False),
    sa.Column('unitCost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['poId'], ['PurchaseOrder.id'], ),
    sa.ForeignKeyConstraint(['productId'], ['Product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_POLine_poId'), 'POLine', ['poId'], unique=False)
    op.create_index(op.f('ix_POLine_productId'), 'POLine', ['productId'], unique=False)
    op.create_table('StockMovement',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('stockItemId', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('RECEIVE', 'SHIP', 'ADJUST', 'TRANSFER', 'DAMAGE', 'COUNT', name='MovementType'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stockItemId'], ['StockItem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_StockMovement_createdAt'), 'StockMovement', ['createdAt'], unique=False)
    op.create_index(op.f('ix_StockMovement_stockItemId'), 'StockMovement', ['stockItemId'], unique=False)
    op.create_index(op.f('ix_StockMovement_tenantId'), 'StockMovement', ['tenantId'], unique=False)
    op.create_index(op.f('ix_StockMovement_type'), 'StockMovement', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_StockMovement_type'), table_name='StockMovement')
    op.drop_index(op.f('ix_StockMovement_tenantId'), table_name='StockMovement')
    op.drop_index(op.f('ix_StockMovement_stockItemId'), table_name='StockMovement')
    op.drop_index(op.f('ix_StockMovement_createdAt'), table_name='StockMovement')
    op.drop_table('StockMovement')
    op.drop_index(op.f('ix_POLine_productId'), table_name='POLine')
    op.drop_index(op.f('ix_POLine_poId'), table_name='POLine')
    op.drop_table('POLine')
    op.drop_index(op.f('ix_VendorProduct_productId'), table_name='VendorProduct')
    op.drop_index(op.f('ix_VendorProduct_isPreferred'), table_name='VendorProduct')
    op.drop_table('VendorProduct')
    op.drop_index(op.f('ix_VendorDocument_vendorId'), table_name='VendorDocument')
    op.drop_index(op.f('ix_VendorDocument_type'), table_name='VendorDocument')
    op.drop_index(op.f('ix_VendorDocument_expiresAt'), table_name='VendorDocument')
    op.drop_table('VendorDocument')
    op.drop_index(op.f('ix_VendorContact_vendorId'), table_name='VendorContact')
    op.drop_index(op.f('ix_VendorContact_role'), table_name='VendorContact')
    op.drop_table('VendorContact')
    op.drop_index(op.f('ix_VendorAddress_vendorId'), table_name='VendorAddress')
    op.drop_index(op.f('ix_VendorAddress_type'), table_name='VendorAddress')
    op.drop_index(op.f('ix_VendorAddress_country'), table_name='VendorAddress')
    op.drop_table('VendorAddress')
    op.drop_index(op.f('ix_StockItem_tenantId'), table_name='StockItem')
    op.drop_index(op.f('ix_StockItem_quantityAvailable'), table_name='StockItem')
    op.drop_index(op.f('ix_StockItem_locationId'), table_name='StockItem')
    op.drop_table('StockItem')
    op.drop_index(op.f('ix_PurchaseOrder_vendorId'), table_name='PurchaseOrder')
    op.drop_index(op.f('ix_PurchaseOrder_tenantId'), table_name='PurchaseOrder')
    op.drop_index(op.f('ix_PurchaseOrder_status'), table_name='PurchaseOrder')
    op.drop_index(op.f('ix_PurchaseOrder_shipmentStatus'), table_name='PurchaseOrder')
    op.drop_index(op.f('ix_PurchaseOrder_poNumber'), table_name='PurchaseOrder')
    op.drop_index(op.f('ix_PurchaseOrder_nextFollowUpAt'), table_name='PurchaseOrder')
    op.drop_table('PurchaseOrder')
    op.drop_index(op.f('ix_ProductImage_productId'), table_name='ProductImage')
    op.drop_index(op.f('ix_ProductImage_position'), table_name='ProductImage')
    op.drop_table('ProductImage')
    op.drop_index(op.f('ix_ProductCategory_productId'), table_name='ProductCategory')
    op.drop_index(op.f('ix_ProductCategory_categoryId'), table_name='ProductCategory')
    op.drop_table('ProductCategory')
    op.drop_index(op.f('ix_ProductAttribute_productId'), table_name='ProductAttribute')
    op.drop_index(op.f('ix_ProductAttribute_name'), table_name='ProductAttribute')
    op.drop_table('ProductAttribute')
    op.drop_index(op.f('ix_OrderLine_productId'), table_name='OrderLine')
    op.drop_index(op.f('ix_OrderLine_orderId'), table_name='OrderLine')
    op.drop_table('OrderLine')
    op.drop_index(op.f('ix_ChannelListing_tenantId'), table_name='ChannelListing')
    op.drop_index(op.f('ix_ChannelListing_status'), table_name='ChannelListing')
    op.drop_index(op.f('ix_ChannelListing_productId'), table_name='ChannelListing')
    op.drop_table('ChannelListing')
    op.drop_index(op.f('ix_Vendor_tier'), table_name='Vendor')
    op.drop_index(op.f('ix_Vendor_tenantId'), table_name='Vendor')
    op.drop_index(op.f('ix_Vendor_isActive'), table_name='Vendor')
    op.drop_index(op.f('ix_Vendor_contractEndDate'), table_name='Vendor')
    op.drop_table('Vendor')
    op.drop_index(op.f('ix_Product_upc'), table_name='Product')
    op.drop_index(op.f('ix_Product_tenantId'), table_name='Product')
    op.drop_index(op.f('ix_Product_status'), table_name='Product')
    op.drop_index(op.f('ix_Product_parentId'), table_name='Product')
    op.drop_index(op.f('ix_Product_brand'), table_name='Product')
    op.drop_index(op.f('ix_Product_asin'), table_name='Product')
    op.drop_table('Product')
    op.drop_index(op.f('ix_Order_tenantId'), table_name='Order')
    op.drop_index(op.f('ix_Order_status'), table_name='Order')
    op.drop_index(op.f('ix_Order_placedAt'), table_name='Order')
    op.drop_table('Order')
    op.drop_index(op.f('ix_Location_type'), table_name='Location')
    op.drop_index(op.f('ix_Location_tenantId'), table_name='Location')
    op.drop_index(op.f('ix_Location_isActive'), table_name='Location')
    op.drop_table('Location')
    op.drop_index(op.f('ix_Category_tenantId'), table_name='Category')
    op.drop_index(op.f('ix_Category_slug'), table_name='Category')
    op.drop_index(op.f('ix_Category_parentId'), table_name='Category')
    op.drop_table('Category')
    # ### end Alembic commands ###
