"""add_tenant_onboarding_complete

Revision ID: aa241d974370
Revises: 45a753191ddf
Create Date: 2026-02-03 21:43:44.794901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa241d974370'
down_revision: Union[str, None] = '45a753191ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('onboarding_complete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'onboarding_complete')
    # ### end Alembic commands ###
